package org.openapitools.configuration;

// =====================================================================================================================
// I M P O R T   S E C T I O N
// =====================================================================================================================
// Spring Boot
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

// =====================================================================================================================
// C O N T R O L L E R   S E C T I O N
// class to redirect the localhost to the actual swagger-ui.html
// auto generated by default, but does not get changed again
// =====================================================================================================================
@Controller
public class HomeController {

    @RequestMapping("/")
    public String index() {
        return "redirect:swagger-ui.html";
    }
    
}